---
- name: set clish
  cli_command: command=clish

- name: set pager
  cli_command: command='set clienv rows 0'

- name: Get hostname 
  cli_command: command='show hostname'
  register: r0

- name: SHOW CONFIG
  cli_command:
    command: "{{ cmd }}"
#  with_lines: cat {{ cmdfile }}
  register: result1

- name: create local dir
#  local_action: file  path=../SHOW/{{ hostvars['localhost']['foo'].stdout }} state=directory
  local_action: file  path={{ logdir | default('../SHOW') }}/{{ hostvars['localhost']['foo'].stdout }} state=directory


- name: Save Output
#  local_action:  copy content={{ result1.stdout }} dest=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt
  local_action:  copy content={{ result1.stdout }} dest={{ logdir | default('../SHOW') }}/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt
  #local_action:  copy content={{ result1['results'].stdout }} dest=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt
  #local_action:  copy content={{ result1['results'].stdout_lines|join('\n') }} dest=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt
  #local_action:  copy content={{ result1.stdout_lines|join('\n') }} dest=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt
