---
#- name: set clish
#  cli_command: command=clish
#
#- name: set pager
#  cli_command: command='set clienv rows 0'
#
- name: Get hostname 
  cli_command: command='hostname'
  register: r0

- name: SHOW CONFIG
  cli_command:
    command: "{{ item }}"
  with_lines: cat {{ cmdfile }}
  register: result1

- name: create dir
  local_action: file  path=../SHOW/{{ hostvars['localhost']['foo'].stdout }} state=directory

- name: write output1
  local_action:  lineinfile path=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt line={{ item.item }} create=yes
  loop: "{{ result1.results }}"

- name: write output2
  local_action:  lineinfile path=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt line="===================================="
  loop: "{{ result1.results }}"

- name: write output3
  local_action:  lineinfile path=../SHOW/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt line={{ item.stdout_lines|join('\n') }}
  loop: "{{ result1.results }}"
