---
# VARIABLES:
#  logdir - Directory where the output of the commands will be stored. This can be specified either relative to the directory where the playbook stored ( ../SHOW) OR the full path (/opt/ansible/SHOW)
# 
#
- name: set clish
  cli_command: command=clish

- name: set pager
  cli_command: command='set clienv rows 0'

- name: Get hostname 
  cli_command: command='show hostname'
  register: r0

- name: SHOW CONFIG
  cli_command: command='show asset all'
  register: result1

- name: create dir
  local_action: file  path={{ logdir | default('../SHOW') }}/{{ hostvars['localhost']['foo'].stdout }} state=directory

- name: write backup
  local_action:  copy content={{ result1.stdout_lines|join('\n') }} dest={{ logdir | default('../SHOW') }}/{{ hostvars['localhost']['foo'].stdout }}/{{ r0.stdout }}.txt

